final List<Map<String, dynamic>> dummyData = [
  {
    "News_ID": 848429,
    "Khabar_Title": "القوات المشتركة تشرع بعملية امنية واسعة في وادي الثرثار",
    "Khabar_Details":
        "بغداد/نينا/ اعلنت خلية الإعلام الأمني عن شروع القوات المشتركة بعملية امنية واسعة في وادي الثرثار./انتهى9",
    "Khabar_Date": "2020-08-08T09:33:00",
    "Author_ID": 167,
    "Menu_ID": 7,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 20,
    "Pic_Title": null,
    "Pic": "",
    "Editor_ID": 143,
    "Director_ID": 143,
    "News_Date2": "2020-08-08T09:31:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848411,
    "Khabar_Title":
        "البيت الأبيض: ترامب يستضيف رئيس وزراء العراق في واشنطن يوم 20 من الشهر الحالي ",
    "Khabar_Details":
        "بغداد/نينا/ اعلن البيت الأبيض أن الرئيس الأمريكي دونالد ترامب سيستقبل رئيس الوزراء العراقي مصطفى الكاظمي في البيت الأبيض يوم 20 آب الشهر الحالي.\r\n\r\nواوضح في بيان اليوم ان الجانبين سيبحثان التحديات الناجمة عن وباء فيروس كورونا وقضايا الأمن والطاقة والاقتصاد./انتهى9",
    "Khabar_Date": "2020-08-08T09:05:00",
    "Author_ID": 167,
    "Menu_ID": 5,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 1,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 62,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848411-55f9f0e6-80df-46db-9732-80b73df7b074.jpg&w=250&h=150&t=absolute",
    "Editor_ID": 143,
    "Director_ID": 143,
    "News_Date2": "2020-08-08T08:41:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848412,
    "Khabar_Title":
        "التربية النيابية: سنعد دراسة بشأن العام الجديد ونستبعد تأجيله",
    "Khabar_Details":
        "بغداد/نينا/ اكد عضو لجنة التربية في مجلس النواب عباس الزاملي ان اللجنة بصدد اعداد دراسة بشأن بدء العام الدراسي الجديد.\r\n\r\nوقال الزاملي في تصريح صحفي \"بالتعاون مع وزارة التربية سيتم اعداد دراسة بشأن بدء العام الدراسي الجديد وتأخر العراق في إنهاء العام الدراسي الحالي، بعد أن فضلت الكثير من الدول إنهائه رغم جائحة كورونا\".\r\n\r\nوأضاف ان \"اللجنة والوزارة ستطرحان مقترحات للتعامل مع الواقع الصحي والاقتصادي كما هو موجود في الوقت الحالي، أو اعتماد التعليم الالكتروني للتلاميذ والطلبة\"، مستبعداً \"تأجيل العام الدراسي الى تواريخ بعيدة أو انتظار زوال كورونا أو اكتشاف لقاح له\"./انتهى10\r\n",
    "Khabar_Date": "2020-08-08T09:03:00",
    "Author_ID": 253,
    "Menu_ID": 9,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 55,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848412-cb8f80d5-7523-4362-8c23-587f4d1d0f8c.jpg&w=250&h=150&t=absolute",
    "Editor_ID": 143,
    "Director_ID": 143,
    "News_Date2": "2020-08-08T08:42:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848413,
    "Khabar_Title": "الكاظمي يوجه بإنجاز مشروع ماء الإصلاح الكبير في ذي قار",
    "Khabar_Details":
        "بغداد/نينا/ وجه رئيس مجلس الوزراء مصطفى الكاظمي، بإنجاز مشروع ماء الإصلاح الكبير في محافظة ذي قار.\r\n\r\nوقالت الامانة العامة لمجلس الوزراء في بيان تلقت الوكالة الوطنية العراقية للانباء /نينا/ نسخة منه ، ان \"رئيس مجلس الوزراء مصطفى الكاظمي وجه خلال جلسة مجلس الوزراء التي عقدت الثلاثاء الماضي، وزارة الإعمار والإسكان والبلديات والأشغال العامة بإكمال مشروع ماء الإصلاح الكبير في ذي قار\".\r\n\r\nواضافت ان \"إنجاز المشروع سوف يحل مشكلة مياه الشرب في منطقة الفهود والأقضية والنواحي القريبة منها\"./انتهى10\r\n",
    "Khabar_Date": "2020-08-08T09:01:00",
    "Author_ID": 253,
    "Menu_ID": 4,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 60,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848413-a4656795-7503-4f8b-8c41-c5b340259f00.jpg&w=250&h=150&t=absolute",
    "Editor_ID": 143,
    "Director_ID": 143,
    "News_Date2": "2020-08-08T08:56:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848359,
    "Khabar_Title": " اندلاع حريق في مستشفى كركوك العام ",
    "Khabar_Details":
        "كركوك /نينا/اندلع حريق في قسم الصيدلة في مستشفى كركوك العام ما ادى لانقطاع الكهرباء بشكل كامل عن المستشفى .\r\n\r\nوقال مصدر صحي ان حريقا اندلع بقسم مذخر الادوية ما تسبب بانقطاع الكهرباء بشكل كامل عن جميع اقسام وردهات المستشفى المخصص لعلاج المصابين بفيروس كورونا الذي يضم اكثر من 250مصابا ومشتبها بهم ./انتهى",
    "Khabar_Date": "2020-08-07T18:31:00",
    "Author_ID": 173,
    "Menu_ID": 9,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 205,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848359-29a8646a-4547-42e4-aa35-60ab93fb2218.jpeg&w=250&h=150&t=absolute",
    "Editor_ID": 27,
    "Director_ID": 27,
    "News_Date2": "2020-08-07T18:25:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848357,
    "Khabar_Title": "نصر الله: نحتاج الان الى الهدوء والتعاطف ولملمة الجراح",
    "Khabar_Details":
        "بغداد/ نينا/ قال الامين العام لحزب الله اللبناني حسن نصر الله اننا نحتاج الان الى الهدوء والتعاطف ولملمة الجراح.\r\n\r\nواضاف نصر الله في كلمة متلفزة اننا لا نملك سلاحا ولا ذخائر ولا عتادا في مرفأ بيروت.\r\n\r\nواوضح ان لا احد يعرف تفاصيل ومسببات انفجار مرفأ بيروت مبينا ان الانفجار اما حادث عرضي او مدبر بفعل فاعل.\r\n\r\nواشار الى ان لبنان يعيش ازمة دولة بسبب الفساد والمحاصصة./انتهى7",
    "Khabar_Date": "2020-08-07T18:11:00",
    "Author_ID": 27,
    "Menu_ID": 5,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 152,
    "Pic_Title": null,
    "Pic": "",
    "Editor_ID": 27,
    "Director_ID": 27,
    "News_Date2": "2020-08-07T18:16:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848341,
    "Khabar_Title":
        "عون :لم اكن اعرف بمكان وجود المواد المتفجرة ولا مدى خطورتها",
    "Khabar_Details":
        "بغداد/ نينا/ قال الرئيس اللبناني ميشال عون انه لم يكن يعرف بمكان وجود المواد المتفجرة ولا مدى خطورتها. \r\n\r\nوقال في مؤتمر صحفي ان المواد المتفجرة كانت موجودة منذ عام 2013.\r\n\r\nواضاف ان المحاكم ستكون مفتوحة امام الكبار والصغار ولن اتوانى عن كشف الحقيقة. \r\n\r\nواشار عون الى ان نظام الحكم الموجود حاليا مصاب بالشلل ونعمل على تغييره./انتهى7",
    "Khabar_Date": "2020-08-07T16:21:00",
    "Author_ID": 27,
    "Menu_ID": 5,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 139,
    "Pic_Title": null,
    "Pic": "",
    "Editor_ID": 27,
    "Director_ID": 27,
    "News_Date2": "2020-08-07T16:24:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848327,
    "Khabar_Title":
        "تسجيل 3461 اصابة جديدة بكورونا و2172 حالة شفاء في عموم العراق",
    "Khabar_Details":
        "بغداد / نينا / اعلنت وزارة الصحة والبيئة عن تسجيل 3461 اصابة جديدة بفايروس كورونا و2172 حالة شفاء في عموم العراق هذا اليوم ./ انتهى5",
    "Khabar_Date": "2020-08-07T15:16:00",
    "Author_ID": 10,
    "Menu_ID": 9,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 178,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848327-350e6223-17ba-4363-a188-c24207b9ff2c.jpg&w=250&h=150&t=absolute",
    "Editor_ID": 10,
    "Director_ID": 10,
    "News_Date2": "2020-08-07T15:20:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848315,
    "Khabar_Title": " النجف تعتذر عن استقبال الزائرين في عيد الغدير ",
    "Khabar_Details":
        "النجف/نينا/ اعلن محافظ النجف لؤي الياسري ، اعتذار المحافظة عن استقبال الزائرين من جميع المحافظات بمناسبة عيد الغدير الاغر.\r\n\r\nووجه الياسري قيادة الشرطة بمعاقبة احدى نقاط التفتيش الخارجية لعدم تطبيق افرادها قرارات خلية الازمة بشكل صحيح./انتهى\r\n",
    "Khabar_Date": "2020-08-07T14:17:00",
    "Author_ID": 179,
    "Menu_ID": 9,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 131,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848315-41455d15-633b-4b38-8709-532b462ac579.jpeg&w=250&h=150&t=absolute",
    "Editor_ID": 10,
    "Director_ID": 10,
    "News_Date2": "2020-08-07T13:57:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
  {
    "News_ID": 848312,
    "Khabar_Title":
        "امام جمعة النجف : الانتخابات خيارنا الدستوري .. وندعو الحكومة لاتخاذ كافة التحضيرات",
    "Khabar_Details":
        "النجف/نينا/ دعا امام وخطيب جمعة النجف صدر الدين القبانجي ، البرلمان الى تعديل قانون الانتخابات ، والحكومة الى اتخاذ الاستعدادات والتحضيرات الكاملة لاجرائها .\r\n\r\nوقال القبانجي في حديث الجمعة الاسبوعي ، الذي يلقيه مجازيا :\" نحن مع الانتخابات لانها خيارنا الدستوري ، و لا خيار آخر \".\r\n\r\n واضاف :\" ندعو البرلمان الى تصويب القانون ، والحكومة الى اتخاذ الاجراءات والتحضيرات، والشعب سيكون مستعدا للمشاركة لتقرير مصيره\". / انتهى",
    "Khabar_Date": "2020-08-07T13:44:00",
    "Author_ID": 179,
    "Menu_ID": 5,
    "Lang_ID": 1,
    "News_Flash": 0,
    "News_Top": 0,
    "Active": 1,
    "Bulletins": null,
    "Bulletins_Ordering": null,
    "Reporter_Approve": 1,
    "Editor_Approve": 1,
    "Director_Approve": 1,
    "Read_Counter": 113,
    "Pic_Title": null,
    "Pic":
        "https://images.weserv.nl/?url=ninanews.com/Uploads/Images/2020/8/848312-ad0fa94d-bfba-48ec-9ad8-a88350349b7d.jpeg&w=250&h=150&t=absolute",
    "Editor_ID": 10,
    "Director_ID": 10,
    "News_Date2": "2020-08-07T13:31:00",
    "Old_Author_ID": null,
    "Old_Editor_ID": null,
    "Old_Director_ID": null,
    "IsBreakingNews": true,
    "Pic_1": null,
    "Pic_2": null,
    "Pic_3": null,
    "Pic_4": null,
    "Pic_5": null,
    "IsNewVersion": 1
  },
];
